service: zorgbort
frameworkVersion: '4'
provider:
  region: us-west-2
  name: aws
  runtime: nodejs22.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    VALID_RELEASE_USERS: ${env:VALID_RELEASE_USERS}
functions:
  slack:
    handler: app.handler
    timeout: 10
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
