name: Update pnpm Version

permissions:
  contents: read

on:
  schedule:
    - cron: "0 13 * * 4" # Weekly on Thursday morning (UTC)
  workflow_dispatch:

jobs:
  update-pnpm:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Update
        run: pnpm self-update
      - name: Get new pnpm version
        run: |
          PNPM_VERSION="$(pnpm --version)"
          echo ${PNPM_VERSION}
          echo "pnpm_version=${PNPM_VERSION}" >> $GITHUB_ENV
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
          commit-message: Update pnpm to v${{ env.pnpm_version }}
          title: Update pnpm to v${{ env.pnpm_version }}
          body: |
            Update pnpm to v${{ env.pnpm_version }} the latest release.
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-pnpm-version
          labels: dependencies
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.ZORGBORT_TOKEN }}
